
package org.example.comparator.agences;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AgenceService", targetNamespace = "http://impl.service.agence.example.org/", wsdlLocation = "http://localhost:8088/StreetMan?wsdl")
public class AgenceService
    extends Service
{

    private final static URL AGENCESERVICE_WSDL_LOCATION;
    private final static WebServiceException AGENCESERVICE_EXCEPTION;
    private final static QName AGENCESERVICE_QNAME = new QName("http://impl.service.agence.example.org/", "AgenceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/StreetMan?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGENCESERVICE_WSDL_LOCATION = url;
        AGENCESERVICE_EXCEPTION = e;
    }

    public AgenceService() {
        super(__getWsdlLocation(), AGENCESERVICE_QNAME);
    }

    public AgenceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGENCESERVICE_QNAME, features);
    }

    public AgenceService(URL wsdlLocation) {
        super(wsdlLocation, AGENCESERVICE_QNAME);
    }

    public AgenceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGENCESERVICE_QNAME, features);
    }

    public AgenceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgenceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IAgence
     */
    @WebEndpoint(name = "AgencePort")
    public IAgence getAgencePort() {
        return super.getPort(new QName("http://impl.service.agence.example.org/", "AgencePort"), IAgence.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAgence
     */
    @WebEndpoint(name = "AgencePort")
    public IAgence getAgencePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.agence.example.org/", "AgencePort"), IAgence.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGENCESERVICE_EXCEPTION!= null) {
            throw AGENCESERVICE_EXCEPTION;
        }
        return AGENCESERVICE_WSDL_LOCATION;
    }

}
