
package org.example.comparator.agences;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IAgence", targetNamespace = "http://interfaces.service.agence.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IAgence {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.util.List<org.example.comparator.agences.Response>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consulterHotel", targetNamespace = "http://interfaces.service.agence.example.org/", className = "org.example.comparator.agences.ConsulterHotel")
    @ResponseWrapper(localName = "consulterHotelResponse", targetNamespace = "http://interfaces.service.agence.example.org/", className = "org.example.comparator.agences.ConsulterHotelResponse")
    @Action(input = "http://interfaces.service.agence.example.org/IAgence/consulterHotelRequest", output = "http://interfaces.service.agence.example.org/IAgence/consulterHotelResponse")
    public List<Response> consulterHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns org.example.comparator.agences.ReservationAgence
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserverChambre", targetNamespace = "http://interfaces.service.agence.example.org/", className = "org.example.comparator.agences.ReserverChambre")
    @ResponseWrapper(localName = "reserverChambreResponse", targetNamespace = "http://interfaces.service.agence.example.org/", className = "org.example.comparator.agences.ReserverChambreResponse")
    @Action(input = "http://interfaces.service.agence.example.org/IAgence/reserverChambreRequest", output = "http://interfaces.service.agence.example.org/IAgence/reserverChambreResponse")
    public ReservationAgence reserverChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        Response arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ClientAgence arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAgenceName", targetNamespace = "http://interfaces.service.agence.example.org/", className = "org.example.comparator.agences.GetAgenceName")
    @ResponseWrapper(localName = "getAgenceNameResponse", targetNamespace = "http://interfaces.service.agence.example.org/", className = "org.example.comparator.agences.GetAgenceNameResponse")
    @Action(input = "http://interfaces.service.agence.example.org/IAgence/getAgenceNameRequest", output = "http://interfaces.service.agence.example.org/IAgence/getAgenceNameResponse")
    public String getAgenceName();

}
